"""Learning objectives + tutor-check question bank.

LOs are adapted from OpenStax *Principles of Microeconomics 3e* chapter
objectives (CC BY 4.0 — see ATTRIBUTION in docs). Question bank is original.
MCQ answers auto-grade; free-response grades via LLM rubric with a keyword
fallback (graceful degradation, DECISIONS.md #7).
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LO:
    """A learning objective: `text` is the full statement (Bloom verb +
    condition + observable behavior) shown where there's room (the Study,
    tooltips); `short` is the compact label for tight UI (heatmap columns,
    chips); `bloom` is the taxonomy level, worn openly."""

    id: str
    chapter: int
    week: int
    short: str
    bloom: str  # Remember | Understand | Apply | Analyze | Evaluate | Create
    text: str


LEARNING_OBJECTIVES: dict[str, LO] = {
    lo.id: lo
    for lo in [
        # Week 1 — Ch.2 scarcity & choice (+ Ch.6 budget threads)
        LO("ch2-opportunity-cost", 2, 1, "Opportunity cost", "Apply",
           "Given two competing uses for the same scarce resource (effort, coins, or cargo space), identify the opportunity cost of a choice as the value of the next-best alternative forgone."),
        LO("ch2-budget-constraint", 2, 1, "Budget constraints", "Apply",
           "Given goods prices and a coin budget, determine which bundles are affordable and describe how a price change re-tilts the tradeoff between goods."),
        LO("ch2-comparative-advantage", 2, 1, "Comparative advantage", "Analyze",
           "Using two producers' opportunity costs, determine who should specialize in which good and explain why voluntary trade leaves both sides better off."),
        LO("ch2-marginal-thinking", 2, 1, "Marginal thinking", "Evaluate",
           "Decide whether to take one more unit of an action by comparing its marginal benefit to its marginal cost, setting sunk costs aside."),
        # Week 2 — Ch.3 demand & supply
        LO("ch3-demand-vs-qd", 3, 2, "Demand vs. quantity", "Understand",
           "Distinguish a change in demand from a change in quantity demanded, and name the events that produce each."),
        LO("ch3-shift-vs-movement", 3, 2, "Shift vs. movement", "Analyze",
           "Given a market event, determine whether it shifts the supply or demand curve or moves the market along a curve, and predict the direction of the change."),
        LO("ch3-equilibrium", 3, 2, "Equilibrium", "Apply",
           "Read equilibrium price and quantity from supply and demand, and explain the pressure that pushes a market back when the price strays from it."),
        LO("ch3-shortage-surplus", 3, 2, "Shortage & surplus", "Apply",
           "Given a price above or below equilibrium, predict whether a shortage or a surplus results and estimate its size from the two curves."),
        # Week 3 — Ch.5 elasticity, price controls
        LO("ch5-elasticity-def", 5, 3, "Price elasticity", "Apply",
           "Compute the price elasticity of demand from a price and quantity change, and classify demand as elastic, inelastic, or unit elastic."),
        LO("ch5-determinants", 5, 3, "Elasticity drivers", "Analyze",
           "Predict whether a good's demand is relatively elastic or inelastic from its substitutes, necessity, budget share, and the time buyers have to adjust."),
        LO("ch5-total-revenue", 5, 3, "Revenue test", "Apply",
           "Use the total revenue test to infer elasticity from how sellers' revenue moves when price changes, and choose a pricing move accordingly."),
        LO("ch3-price-ceiling", 3, 3, "Price controls", "Analyze",
           "Predict the consequences of a binding price ceiling or floor: the change in quantity traded, the shortage or surplus created, and who queues, rations, or exits."),
        LO("ch3-deadweight", 3, 3, "Deadweight loss", "Understand",
           "Explain why trades blocked by a price control destroy value for both buyers and sellers — deadweight loss — rather than merely redistributing it."),
        # Week 4 — Ch.7 production & costs
        LO("ch7-fixed-variable", 7, 4, "Cost types", "Apply",
           "Classify a producer's costs as fixed, variable, or marginal, and compute each from a simple cost table or story."),
        LO("ch7-diminishing-returns", 7, 4, "Diminishing returns", "Analyze",
           "Explain why each added worker raises output by less when some input is fixed, and detect diminishing marginal returns in production data."),
        LO("ch7-average-cost", 7, 4, "Marginal vs. average", "Understand",
           "Explain how marginal cost pulls average cost up or down, and locate the output level where average cost bottoms out."),
        LO("ch7-breakeven-shutdown", 7, 4, "Shutdown logic", "Evaluate",
           "Given prices and costs, judge whether a producer should keep operating at a loss, shut down for now, or exit — separating fixed costs from avoidable ones."),
        # Week 5 — Ch.8/9 competition & monopoly
        LO("ch8-price-taker", 8, 5, "Price takers", "Understand",
           "Explain why a seller facing many rivals offering the same good cannot sustain a price above the market's, and what happens if they try."),
        LO("ch9-barriers", 9, 5, "Entry barriers", "Analyze",
           "Identify barriers to entry — licenses, scale, exclusive inputs — and explain how each one protects a monopolist's markup from competition."),
        LO("ch9-mr-lt-p", 9, 5, "Monopoly MR", "Understand",
           "Explain why a monopolist's marginal revenue lies below its price whenever selling one more unit requires cutting the price on all units."),
        LO("ch9-entry-profits", 9, 5, "Entry & profits", "Apply",
           "Predict how the entry of new sellers moves prices, output, and profits in a market that is earning above-normal returns."),
        # Week 6 — Ch.12/13 externalities & commons
        LO("ch12-private-social", 12, 6, "Private vs. social cost", "Understand",
           "Distinguish the private cost a producer pays from the social cost that includes harm to bystanders, and identify the wedge an externality drives between them."),
        LO("ch12-pigouvian", 12, 6, "Corrective taxes", "Apply",
           "Predict how a per-unit tax set equal to the external harm changes a polluter's production and abatement choices, and explain why it corrects the incentive."),
        LO("ch13-commons", 13, 6, "The commons", "Analyze",
           "Explain why open access leads each user to overuse a shared resource even while the group is worse off, and evaluate fixes such as quotas, permits, and ownership."),
        LO("ch13-public-goods", 13, 6, "Public goods", "Understand",
           "Explain why goods that are non-excludable invite free riding and end up underprovided when funded by voluntary contribution."),
        # Week 7 — Ch.10/11 oligopoly & antitrust
        LO("ch10-interdependence", 10, 7, "Oligopoly strategy", "Analyze",
           "Explain how one seller's best move depends on rivals' choices, and use a simple payoff table to find the likely outcome of the strategic game."),
        LO("ch10-cartel-cheating", 10, 7, "Cartels & cheating", "Analyze",
           "Explain why cartels form, why each member is individually tempted to undercut the agreement, and what conditions make collusion fragile."),
        LO("ch10-differentiation", 10, 7, "Differentiation", "Understand",
           "Describe how differentiating a product gives a seller a little pricing power even when many competitors are nearby."),
        LO("ch11-antitrust", 11, 7, "Antitrust", "Evaluate",
           "Judge when market concentration harms buyers, and match antitrust remedies — fines, divestiture, blocked mergers — to the specific harm they address."),
    ]
}


@dataclass(frozen=True)
class Question:
    id: str
    week: int
    los: tuple[str, ...]
    kind: str               # mcq | free
    prompt: str
    choices: tuple[str, ...] = ()
    answer: int = -1        # index into choices (mcq)
    rubric: str = ""        # grading rubric (free)
    keywords: tuple[str, ...] = ()  # fallback grading (free)
    context_tags: tuple[str, ...] = ()  # gameplay hooks: trade, ceiling, festival...
    diagram: dict | None = None  # chart spec the client renders (see ui Diagram)


# Diagram spec contract (rendered by the frontend's <Diagram/>):
#   {"xlab": str, "ylab": str,
#    "lines": [{"pts": [[x,y],...], "label": str, "color": "sage|terracotta|sky|ink",
#               "dashed": bool?}],
#    "hline": {"p": int, "label": str}?,
#    "points": [{"q": x, "p": y, "label": str}]?,
#    "guides": [{"q": x, "p": y}]?}          # dotted droplines to both axes
# All coordinates live in a 0-100 data space.

_SD = {  # the workhorse: supply p=q, demand p=100-q, equilibrium at (50,50)
    "xlab": "Quantity", "ylab": "Price",
    "lines": [
        {"pts": [[0, 0], [100, 100]], "label": "S", "color": "sage"},
        {"pts": [[0, 100], [100, 0]], "label": "D", "color": "terracotta"},
    ],
    "points": [{"q": 50, "p": 50, "label": "E"}],
}


QUESTIONS: dict[str, Question] = {
    q.id: q
    for q in [
        # ---- Week 1
        Question("w1-opp-1", 1, ("ch2-opportunity-cost",), "mcq",
                 "You spent 10 effort gathering wool instead of grain. The opportunity cost of that wool is:",
                 ("The coins you could sell the wool for",
                  "The grain you could have gathered with that same effort",
                  "Nothing — effort renews daily",
                  "The effort itself"),
                 1, context_tags=("gathered",)),
        Question("w1-opp-2", 1, ("ch2-opportunity-cost", "ch2-marginal-thinking"), "mcq",
                 "When does it make sense to spend one MORE effort point fishing?",
                 ("Whenever you enjoy fishing",
                  "When the expected catch is worth more to you than your best alternative use of that effort",
                  "Only when fish prices are rising",
                  "Whenever your effort bar is full"),
                 1, context_tags=("fishing_cast",)),
        Question("w1-trade-1", 1, ("ch2-comparative-advantage",), "mcq",
                 "You gather wool 3x faster than grain; your classmate gathers grain 3x faster than wool. Trading wool-for-grain makes:",
                 ("Only you better off", "Only them better off",
                  "Both of you better off", "Neither — trade just moves goods around"),
                 2, context_tags=("trade",)),
        Question("w1-budget-1", 1, ("ch2-budget-constraint",), "mcq",
                 "With 100 coins, grain at 25 and wool at 50, which bundle is NOT affordable?",
                 ("4 grain", "2 wool", "2 grain and 1 wool", "3 grain and 1 wool"),
                 3),
        Question("w1-free-1", 1, ("ch2-comparative-advantage",), "free",
                 "In one sentence: why did the Traveling Merchant make money buying cloth in Milltown and selling it in Saltharbor?",
                 rubric="Credit answers identifying price differences across locations / buying low & selling high / arbitrage.",
                 keywords=("price", "cheap", "low", "high", "differ", "arbitrage"),
                 context_tags=("merchant_completed",)),
        # ---- Week 2
        Question("w2-shift-1", 2, ("ch3-shift-vs-movement",), "mcq",
                 "The Lantern Festival raised garment prices. On the garment market diagram, the festival itself was:",
                 ("A movement along the demand curve", "A rightward shift of the demand curve",
                  "A leftward shift of the supply curve", "A movement along the supply curve"),
                 1, context_tags=("festival",)),
        Question("w2-shift-2", 2, ("ch3-shift-vs-movement",), "mcq",
                 "After the festival prices rose, more students started producing garments. That response was:",
                 ("A shift of demand", "A shift of supply over time",
                  "A movement along demand only", "Deadweight loss"),
                 1, context_tags=("festival",)),
        Question("w2-eq-1", 2, ("ch3-equilibrium",), "mcq",
                 "In your order-book market, the 'market price' is best described as:",
                 ("Whatever the Crown decrees", "The price where arriving bids and asks keep crossing",
                  "The average of all prices ever traded", "The highest ask anyone posts"),
                 1, context_tags=("trade",)),
        Question("w2-shortage-1", 2, ("ch3-shortage-surplus",), "mcq",
                 "During the festival rush you saw bids piling up unfilled. That is the textbook picture of:",
                 ("A surplus", "A shortage at the current price", "Equilibrium", "Elastic demand"),
                 1, context_tags=("festival", "shortage")),
        Question("w2-demand-qd", 2, ("ch3-demand-vs-qd",), "mcq",
                 "Bread got cheaper and you bought more bread. Your demand curve for bread:",
                 ("Shifted right", "Shifted left",
                  "Did not move — you moved along it", "Became more elastic"),
                 2),
        Question("w2-free-1", 2, ("ch3-equilibrium", "ch3-shortage-surplus"), "free",
                 "Look at your garment price chart from festival week. In 1-2 sentences, tell the story of what happened and why.",
                 rubric="Credit: demand shift up at announcement/festival, price spike, supply response with lag, post-festival glut/fall.",
                 keywords=("demand", "spike", "rose", "supply", "fell", "glut", "festival"),
                 context_tags=("festival",)),
        # ---- Week 3
        Question("w3-elastic-1", 3, ("ch5-determinants",), "mcq",
                 "Medicine stayed expensive during the drought but people kept buying. Tapestry sales collapsed when prices rose. Why?",
                 ("Medicine demand is elastic; tapestry demand is inelastic",
                  "Medicine demand is inelastic (a necessity); tapestry demand is elastic (a luxury)",
                  "Both are inelastic", "The Crown subsidizes medicine"),
                 1, context_tags=("drought",)),
        Question("w3-tr-1", 3, ("ch5-total-revenue",), "mcq",
                 "You raised your shop's bread price 20% and your bread REVENUE fell. Demand for your bread is:",
                 ("Inelastic", "Elastic", "Unit elastic", "Perfectly inelastic"),
                 1, context_tags=("shop_sale",)),
        Question("w3-ceiling-1", 3, ("ch3-price-ceiling",), "mcq",
                 "The Bread Decree capped bread at its old price during a grain drought. The empty shelves happened because:",
                 ("Bakers forgot how to bake",
                  "At the legal price, quantity demanded exceeded what sellers would supply",
                  "The Crown bought all the bread", "Demand fell"),
                 1, context_tags=("ceiling", "shortage")),
        Question("w3-ceiling-2", 3, ("ch3-price-ceiling", "ch3-deadweight"), "mcq",
                 "Who was helped by the Bread Decree?",
                 ("Everyone", "Bakers",
                  "The few buyers who got bread at the legal price",
                  "Buyers who found only empty shelves"),
                 2, context_tags=("ceiling",)),
        Question("w3-elastic-def", 3, ("ch5-elasticity-def",), "mcq",
                 "Price rises 10%, quantity demanded falls 30%. Price elasticity of demand is (in magnitude):",
                 ("0.33 — inelastic", "1.0 — unit", "3.0 — elastic", "30 — perfectly elastic"),
                 2),
        Question("w3-free-1", 3, ("ch3-price-ceiling",), "free",
                 "A classmate says 'the bread ceiling kept bread affordable.' In 1-2 sentences, what did it actually do in your world?",
                 rubric="Credit: shortage/empty shelves, sellers withdrew, hard to buy at any legal price, possibly gray market.",
                 keywords=("shortage", "empty", "withdrew", "couldn't buy", "stopped selling", "gray"),
                 context_tags=("ceiling",)),
        # ---- Week 4
        Question("w4-fc-1", 4, ("ch7-fixed-variable",), "mcq",
                 "Your bakery's build cost vs the flour it consumes daily are, respectively:",
                 ("Both fixed costs", "Both variable costs",
                  "Fixed cost; variable cost", "Variable cost; fixed cost"),
                 2, context_tags=("facility_built",)),
        Question("w4-dim-1", 4, ("ch7-diminishing-returns",), "mcq",
                 "Each worker you add to the smithy raises output by less than the one before. That is:",
                 ("Economies of scale", "Diminishing marginal returns",
                  "Diseconomies of scope", "Deadweight loss"),
                 1, context_tags=("workers_set",)),
        Question("w4-shut-1", 4, ("ch7-breakeven-shutdown",), "mcq",
                 "Demand slumped and your factory's output sells below its input + upkeep cost. For THIS WEEK you should:",
                 ("Produce anyway — you paid for the factory",
                  "Idle the facility: the build cost is sunk; avoid the variable losses",
                  "Sell the factory immediately", "Raise your prices to cover costs"),
                 1, context_tags=("demand_shock",)),
        Question("w4-mc-1", 4, ("ch7-average-cost",), "mcq",
                 "A charter factory has huge build cost but cheap per-unit production. Its average cost per unit ___ as output grows.",
                 ("Rises", "Falls (the fixed cost spreads over more units)",
                  "Stays constant", "Equals marginal cost always"),
                 1),
        Question("w4-free-1", 4, ("ch7-breakeven-shutdown",), "free",
                 "You chose charter or artisan this week. In a sentence: what would have to happen to demand for the OTHER choice to have been better?",
                 rubric="Charter wins with high sustained demand (spread fixed costs); artisan wins when demand is low/volatile.",
                 keywords=("demand", "high", "low", "fixed", "volume", "spread"),
                 context_tags=("facility_built",)),
        # ---- Week 5
        Question("w5-taker-1", 5, ("ch8-price-taker",), "mcq",
                 "In the grain market no single student can move the price. Each seller there is:",
                 ("A monopolist", "A price taker", "A price maker", "A cartel"),
                 1),
        Question("w5-barrier-1", 5, ("ch9-barriers",), "mcq",
                 "Glowdye sellers earn fat margins; grain sellers don't. The difference is:",
                 ("Glowdye is prettier", "A legal barrier to entry — the Crown license",
                  "Grain is harder to make", "Glowdye buyers are richer"),
                 1, context_tags=("license_granted",)),
        Question("w5-mr-1", 5, ("ch9-mr-lt-p",), "mcq",
                 "As the only glowdye seller, selling one more unit means dropping your price on ALL units. Your marginal revenue is therefore:",
                 ("Above the price", "Equal to the price", "Below the price", "Zero"),
                 2, context_tags=("license_granted",)),
        Question("w5-entry-1", 5, ("ch9-entry-profits",), "mcq",
                 "The Second Charter added new glowdye licenses. Prices and incumbent profits should:",
                 ("Both rise", "Both fall toward the competitive level",
                  "Stay the same", "Become more volatile only"),
                 1, context_tags=("license_granted",)),
        Question("w5-free-1", 5, ("ch9-mr-lt-p", "ch9-entry-profits"), "free",
                 "You hold a glowdye license and more licenses are coming. Price high now or low for loyalty? Defend your choice in a sentence.",
                 rubric="Either defensible: harvest surplus before entry vs deter/lock demand pre-entry. Credit recognition of the entry threat.",
                 keywords=("entry", "competition", "before", "loyal", "harvest", "margin"),
                 context_tags=("license_granted",)),
        # ---- Week 6
        Question("w6-ext-1", 6, ("ch12-private-social",), "mcq",
                 "Your smelter's smog slows EVERYONE's facilities. Your private cost of smelting differs from social cost by:",
                 ("Nothing", "The upkeep you pay",
                  "The damage your smog does to others", "The smog tax"),
                 2, context_tags=("production",)),
        Question("w6-pigou-1", 6, ("ch12-pigouvian",), "mcq",
                 "The soot levy charges per unit of smoke. Economists like this because it:",
                 ("Punishes the rich", "Makes polluters face the social cost of their choices",
                  "Raises revenue for the Crown", "Bans pollution outright"),
                 1, context_tags=("smog_tax",)),
        Question("w6-commons-1", 6, ("ch13-commons",), "mcq",
                 "The fishery collapsed even though every student would prefer it healthy. Why?",
                 ("Students are irrational",
                  "Each fisher keeps the whole benefit of a catch but shares the cost of depletion",
                  "Fish prices were too low", "The Crown overfished"),
                 1, context_tags=("fishery",)),
        Question("w6-commons-2", 6, ("ch13-commons",), "mcq",
                 "Which fixes open-access overfishing WITHOUT closing the fishery?",
                 ("A subsidy on fish", "Quotas or tradable catch shares",
                  "A price ceiling on fish", "Advertising"),
                 1, context_tags=("fishery",)),
        Question("w6-free-1", 6, ("ch13-public-goods",), "free",
                 "The lighthouse subscription raised less than the lighthouse benefits the town. In a sentence, why?",
                 rubric="Free riding: non-payers can't be excluded from the benefit, so people understate willingness to pay.",
                 keywords=("free ride", "free-rid", "everyone benefits", "can't exclude", "non-exclud", "others pay"),
                 context_tags=()),
        # ---- Week 7
        Question("w7-cartel-1", 7, ("ch10-cartel-cheating",), "mcq",
                 "Your price accord holds garments at 200. Each member's strongest private temptation is to:",
                 ("Raise the price to 250", "Quietly sell below 200 and capture volume",
                  "Leave the market", "Buy garments"),
                 1, context_tags=("compact_created",)),
        Question("w7-inter-1", 7, ("ch10-interdependence",), "mcq",
                 "In the Market Wars, your best price depends on what rival houses charge. That is the defining feature of:",
                 ("Perfect competition", "Monopoly", "Oligopoly", "A commons"),
                 2, context_tags=("tournament_start",)),
        Question("w7-diff-1", 7, ("ch10-differentiation",), "mcq",
                 "Custom tapestry patterns command premiums over plain cloth because differentiation:",
                 ("Eliminates competition entirely",
                  "Gives each maker a little price-setting power over their own variety",
                  "Lowers production costs", "Is required by the Guild"),
                 1, context_tags=("crafted",)),
        Question("w7-anti-1", 7, ("ch11-antitrust",), "mcq",
                 "The Crown's antitrust suit forced a hoarder to divest iron. The economic argument FOR doing this is:",
                 ("Hoarders are unpopular",
                  "Restoring competition moves price and quantity toward the efficient outcome",
                  "The Crown needed the iron", "It raises tax revenue"),
                 1, context_tags=("antitrust",)),
        Question("w7-free-1", 7, ("ch10-cartel-cheating",), "free",
                 "Your cartel collapsed (or held!). In 1-2 sentences, explain the prisoner's dilemma your compact faced.",
                 rubric="Credit: individually rational to defect/undercut though collectively better to cooperate; trust/enforcement absent.",
                 keywords=("defect", "cheat", "undercut", "cooperate", "trust", "tempt"),
                 context_tags=("compact_created",)),
        # ---- Depth pass, week 1: scarcity, budgets, trade, margins ----
        Question("w1-opp-3", 1, ("ch2-opportunity-cost",), "mcq",
                 "You have 6 effort left. Casting twice would land about 2 fish (worth ~35c each); the same effort gathers 3 wool (~30c each). The opportunity cost of choosing to fish is:",
                 ("The ~90c of wool you didn't gather",
                  "The 3 effort each cast consumed",
                  "The ~70c the fish will fetch",
                  "Nothing — effort returns at dawn anyway"),
                 0, context_tags=("fishing_cast",)),
        Question("w1-opp-4", 1, ("ch2-opportunity-cost",), "mcq",
                 "Your wagon arrived loaded with 30 free wool. The opportunity cost of KEEPING it on your shelf today is:",
                 ("The coins the market would pay for it right now",
                  "Zero — it came free with the wagon",
                  "The effort someone once spent shearing it",
                  "Whatever you originally paid for it"),
                 0),
        Question("w1-opp-free", 1, ("ch2-opportunity-cost",), "free",
                 "A classmate says the daily puzzle is 'free effort — it costs nothing to play.' In a sentence: what does playing it actually cost, and why might it still be worth it?",
                 rubric="Credit answers naming time/attention that could go to a next-best alternative (opportunity cost), and weighing that against the reward.",
                 keywords=("time", "instead", "alternative", "forgone", "else",
                           "opportunity")),
        Question("w1-budget-2", 1, ("ch2-budget-constraint",), "mcq",
                 "You hold 120 coins. Bread costs 60, medicine costs 60. Which bundle lands exactly ON your budget line?",
                 ("1 bread and 1 medicine (120)",
                  "2 bread and 1 medicine (180)",
                  "1 bread and 2 medicine (180)",
                  "3 bread (180)"),
                 0),
        Question("w1-budget-3", 1, ("ch2-budget-constraint",), "mcq",
                 "Grain costs 25, wool costs 50. Along your budget line, giving up one wool frees enough coin for:",
                 ("2 grain", "Half a grain", "1 grain", "4 grain"),
                 0),
        Question("w1-budget-4", 1, ("ch2-budget-constraint",), "mcq",
                 "Overnight, bread's price doubles while your coins and every other price stay put. Your set of affordable bundles:",
                 ("Shrinks, and tilts away from bread — each loaf now costs twice as much of everything else",
                  "Is unchanged — coins are coins",
                  "Grows, because bread is now more valuable",
                  "Shrinks by the same amount in every good"),
                 0),
        Question("w1-budget-diag", 1, ("ch2-budget-constraint",), "mcq",
                 "Your coins buy any bundle on or under the budget line. Which marked bundle is out of reach?",
                 ("C — beyond the line: it costs more than your purse holds",
                  "A — it sits exactly on the line",
                  "B — it sits inside the line",
                  "None; every drawn point is affordable"),
                 0,
                 diagram={"xlab": "Wool", "ylab": "Grain",
                          "lines": [
                              {"pts": [[0, 80], [80, 0]], "label": "Budget",
                               "color": "ink"},
                          ],
                          "points": [{"q": 30, "p": 50, "label": "A"},
                                     {"q": 20, "p": 20, "label": "B"},
                                     {"q": 70, "p": 40, "label": "C"}]}),
        Question("w1-trade-2", 1, ("ch2-comparative-advantage",), "mcq",
                 "Rina gathers 4 grain or 2 wool per effort; you gather 1 grain or 1 wool. She beats you at BOTH. Who should specialize in wool?",
                 ("You — your wool costs you 1 grain, hers costs her 2",
                  "Rina — she is better at everything",
                  "Neither — trade can't help when one side dominates",
                  "Both should split their time evenly"),
                 0),
        Question("w1-trade-3", 1, ("ch2-comparative-advantage",), "mcq",
                 "Nobody in the Agora is forced to the trading table. So a completed trade tells you:",
                 ("Both sides expected to gain, or no hands would have shaken",
                  "The seller won and the buyer lost",
                  "The buyer won and the seller lost",
                  "Exactly one side was fooled"),
                 0, context_tags=("trade",)),
        Question("w1-trade-free", 1, ("ch2-comparative-advantage",), "free",
                 "Your aptitude gives you triple yield in one good. In a sentence or two: why does the whole town end up richer when you gather your specialty and trade, instead of making a little of everything yourself?",
                 rubric="Credit: specializing where opportunity cost is lowest raises total output; trade then shares the gains.",
                 keywords=("specializ", "advantage", "cheaper", "more", "trade",
                           "cost"),
                 context_tags=("gathered",)),
        Question("w1-marg-2", 1, ("ch2-marginal-thinking",), "mcq",
                 "You paid 120c for a farm yesterday and rather regret it. When deciding whether to work it TODAY, the 120c should:",
                 ("Not count at all — it's spent either way; weigh today's benefits against today's costs",
                  "Count double, as a lesson",
                  "Count in full against today's harvest",
                  "Be added to the price of tomorrow's grain"),
                 0),
        Question("w1-marg-3", 1, ("ch2-marginal-thinking",), "mcq",
                 "A caravan pays 60c each for up to 5 tools. Your first three cost 40c of inputs apiece; rushing two more would cost 70c apiece. How many do you sell?",
                 ("3 — sell while the marginal 60c beats the marginal cost, stop when it doesn't",
                  "5 — a sale is a sale",
                  "0 — rush work is never worth it",
                  "4 — split the difference"),
                 0, context_tags=("haggle_closed",)),
        Question("w1-marg-4", 1, ("ch2-marginal-thinking",), "mcq",
                 "Fifth cast of the day, and each cast has been landing less than the one before. When should you stop for the day?",
                 ("When the next cast's expected haul is worth less than that effort's best other use",
                  "When your effort bar hits exactly zero",
                  "Never — fish are free",
                  "After three casts; three is traditional"),
                 0, context_tags=("fishing_cast",)),
        Question("w1-marg-free", 1, ("ch2-marginal-thinking",), "free",
                 "In a sentence: why is \"I've already sunk 200 coppers into this shop, so I have to keep stocking it\" bad economics?",
                 rubric="Credit: sunk costs are unrecoverable and irrelevant; only future marginal costs and benefits should drive the decision.",
                 keywords=("sunk", "past", "future", "marginal", "ignore",
                           "gone")),
        # ---- Depth pass, week 2: demand, supply, equilibrium ----
        Question("w2-dvq-2", 2, ("ch3-demand-vs-qd",), "mcq",
                 "Bread's price falls from 60 to 45 and shoppers carry home more loaves. Nothing else changed. What increased?",
                 ("Quantity demanded — a slide along the same demand curve",
                  "Demand — the whole curve moved",
                  "Both demand and quantity demanded",
                  "Supply"),
                 0),
        Question("w2-dvq-3", 2, ("ch3-demand-vs-qd",), "mcq",
                 "The Crier reports a sudden fashion for tapestries — buyers want more at every price. What increased?",
                 ("Demand — the whole curve moved right",
                  "Quantity demanded only",
                  "Supply",
                  "Nothing, until the price actually changes"),
                 0, context_tags=("festival",)),
        Question("w2-dvq-free", 2, ("ch3-demand-vs-qd",), "free",
                 "A classmate says \"demand went up because the price dropped.\" In a sentence, untangle what they've mixed up.",
                 rubric="Credit: a price change moves quantity demanded along the curve; 'demand' shifts only from non-price causes (tastes, income, expectations…).",
                 keywords=("quantity", "curve", "shift", "along", "price")),
        Question("w2-shift-4", 2, ("ch3-shift-vs-movement",), "mcq",
                 "New, cheaper looms cut every weaver's costs. In the cloth market, this:",
                 ("Shifts supply right — more cloth offered at every price",
                  "Shifts demand right",
                  "Causes a movement along the supply curve",
                  "Shifts supply left"),
                 0),
        Question("w2-shift-5", 2, ("ch3-shift-vs-movement",), "mcq",
                 "Which of these is a MOVEMENT along a curve, not a shift?",
                 ("Cloth's price falls, and buyers step up their cloth purchases",
                  "A festival raises garment demand at every price",
                  "A drought cuts the grain harvest",
                  "Three new bakers enter the bread trade"),
                 0),
        Question("w2-eq-5", 2, ("ch3-equilibrium",), "mcq",
                 "At today's close, bread sellers sit on unsold loaves at the going price. Tomorrow, expect:",
                 ("The price to drift down as sellers undercut one another",
                  "The price to rise — bread is scarce",
                  "No change; closing prices are final",
                  "The Crown to step in; markets can't fix this"),
                 0),
        # ---- Depth pass, week 3: elasticity, controls, deadweight ----
        Question("w3-elast-3", 3, ("ch5-elasticity-def",), "mcq",
                 "Garments rise 10% in price and the quantity sold falls 25%. Elasticity ≈ 2.5, so demand is:",
                 ("Elastic — quantity swings proportionally more than price",
                  "Inelastic",
                  "Unit elastic",
                  "Perfectly inelastic"),
                 0),
        Question("w3-elast-4", 3, ("ch5-elasticity-def",), "mcq",
                 "Medicine climbs 20% in price and sales dip only 4%. The elasticity is about:",
                 ("0.2 — deeply inelastic",
                  "5 — highly elastic",
                  "1 — unit elastic",
                  "0 — perfectly elastic"),
                 0),
        Question("w3-elast-free", 3, ("ch5-elasticity-def",), "free",
                 "In a sentence: why does \"just raise your price and you'll make more money\" only work for some goods?",
                 rubric="Credit: it depends on elasticity — with elastic demand the lost quantity outweighs the higher price; with inelastic demand it doesn't.",
                 keywords=("elastic", "inelastic", "quantity", "revenue",
                           "depends", "lose")),
        Question("w3-det-3", 3, ("ch5-determinants",), "mcq",
                 "Which demand is likely MOST price-elastic?",
                 ("Tapestries — a luxury with an easy substitute (bare walls are free)",
                  "Medicine for the town's sick",
                  "Bread, the daily staple",
                  "They're all equally elastic"),
                 0),
        Question("w3-det-4", 3, ("ch5-determinants",), "mcq",
                 "A levy makes charcoal dear. Demand for charcoal will be:",
                 ("More elastic next season than this week — buyers need time to find substitutes",
                  "More elastic today than later",
                  "Equally elastic at every horizon",
                  "Perfectly inelastic forever"),
                 0),
        Question("w3-det-5", 3, ("ch5-determinants",), "mcq",
                 "A 10% rise in the price of sewing pins versus a 10% rise in your shop's rent: which changes your behavior more?",
                 ("The rent — it claims a large share of the budget, so buyers respond hard",
                  "The pins — small things sting most",
                  "Both equally; ten percent is ten percent",
                  "Neither; behavior ignores prices"),
                 0),
        Question("w3-tr-3", 3, ("ch5-total-revenue",), "mcq",
                 "You cut garment prices 15% and your till collects MORE than before. Your demand was:",
                 ("Elastic — the extra sales outweighed the discount",
                  "Inelastic — buyers barely noticed",
                  "Unit elastic — revenue never moves",
                  "Vertical"),
                 0),
        Question("w3-tr-4", 3, ("ch5-total-revenue",), "mcq",
                 "Bread demand in the Agora is inelastic. A bakers' ring that raises prices will see revenue:",
                 ("Rise — few buyers walk away from the staple",
                  "Fall — buyers flee to substitutes",
                  "Stay exactly flat",
                  "Drop to zero"),
                 0),
        Question("w3-tr-free", 3, ("ch5-total-revenue",), "free",
                 "You just sold the caravan visitor 4 cloth at your quoted price. In a sentence: how would knowing the elasticity of THEIR demand have helped you choose the quote?",
                 rubric="Credit: an inelastic buyer tolerates a higher quote with little lost volume; elasticity tells you how price changes move total revenue.",
                 keywords=("elastic", "higher", "revenue", "willing", "limit",
                           "quote"),
                 context_tags=("haggle_closed",)),
        Question("w3-dwl-2", 3, ("ch3-deadweight",), "mcq",
                 "Under the Bread Decree, Rina values a loaf at 80 and a baker can make one for 45 — but the legal price is 30 and the shelves are bare. The blocked trade destroys:",
                 ("35 of combined value that now no one gets",
                  "Nothing — the coins stay in town",
                  "Only the baker's profit",
                  "Only Rina's enjoyment"),
                 0, context_tags=("ceiling",)),
        Question("w3-dwl-3", 3, ("ch3-deadweight",), "mcq",
                 "Deadweight loss is best described as:",
                 ("Gains from trade that vanish because the trades never happen",
                  "Money transferred from sellers to buyers",
                  "Revenue collected by the Crown",
                  "Profits captured by monopolists"),
                 0),
        Question("w3-dwl-4", 3, ("ch3-deadweight",), "mcq",
                 "Which of these creates deadweight loss?",
                 ("A ceiling that blocks bakers and buyers who would both happily trade above it",
                  "The Crier posting yesterday's prices in the square",
                  "Trades both sides walk into freely",
                  "Repealing a binding ceiling"),
                 0, context_tags=("ceiling",)),
        Question("w3-dwl-free", 3, ("ch3-deadweight", "ch3-price-ceiling"), "free",
                 "The Bread Decree capped prices \"to help buyers.\" In a sentence or two, explain how buyers themselves can end up worse off.",
                 rubric="Credit: shortage means many can't buy at any legal price; queueing, rationing, gray markets add costs; blocked trades destroy value buyers would have enjoyed.",
                 keywords=("shortage", "queue", "black", "unavailable", "less",
                           "empty"),
                 context_tags=("ceiling", "shortage")),
        # ---- Depth pass, week 4: production & costs ----
        Question("w4-cost-2", 4, ("ch7-fixed-variable",), "mcq",
                 "Your mill owes 14c upkeep tonight whether it runs or not, plus 6c of grain per sack of flour. Producing 4 sacks costs:",
                 ("38c in total — 14 fixed plus 24 variable",
                  "24c — only what varies counts",
                  "14c — upkeep is the real cost",
                  "56c — 14 for each sack"),
                 0),
        Question("w4-cost-3", 4, ("ch7-fixed-variable",), "mcq",
                 "Same mill: what is the MARGINAL cost of the fifth sack?",
                 ("6c — just the extra grain it takes",
                  "14c — the upkeep",
                  "20c — upkeep plus grain",
                  "44c divided by five"),
                 0),
        Question("w4-cost-4", 4, ("ch7-fixed-variable",), "mcq",
                 "Which of these is a FIXED cost of your workshop?",
                 ("The nightly upkeep owed even when nothing is produced",
                  "Ingredients used per unit produced",
                  "The wage of the extra worker you hire only on busy days",
                  "The soot levy charged per unit of smoke"),
                 0),
        Question("w4-dr-3", 4, ("ch7-diminishing-returns",), "mcq",
                 "Workers and output: 1→10, 2→18, 3→24, 4→28. The marginal product of the fourth worker is:",
                 ("4 sacks", "28 sacks", "7 sacks", "10 sacks"),
                 0, context_tags=("workers",)),
        Question("w4-dr-4", 4, ("ch7-diminishing-returns",), "mcq",
                 "Why does the fourth worker add less than the second in the same loom-house?",
                 ("The looms and floor space are fixed, so extra hands share the same tools",
                  "Later hires are lazier by nature",
                  "Wages rise with each hire",
                  "Cloth prices fall as you produce"),
                 0, context_tags=("workers",)),
        Question("w4-dr-free", 4, ("ch7-diminishing-returns",), "free",
                 "You doubled your workers but output rose only 30%. In a sentence: what would you check before blaming the workers?",
                 rubric="Credit: some input is fixed (facility tier, tools, space) so marginal returns diminish; the fix is more capital, not scolding.",
                 keywords=("fixed", "space", "tools", "capital", "crowd",
                           "diminish", "tier"),
                 context_tags=("workers",)),
        Question("w4-ac-2", 4, ("ch7-average-cost",), "mcq",
                 "Your bakery's average cost is 20c a loaf. The NEXT loaf would cost 12c. Baking it moves average cost:",
                 ("Down — a below-average addition pulls the average down",
                  "Up — more output always costs more",
                  "Nowhere — averages don't move",
                  "To exactly 12c"),
                 0),
        Question("w4-ac-3", 4, ("ch7-average-cost",), "mcq",
                 "Now the next loaf would cost 26c against a 20c average. Baking it moves average cost:",
                 ("Up — an above-average addition drags the average up",
                  "Down — spreading fixed costs always helps",
                  "Nowhere",
                  "To exactly 26c"),
                 0),
        Question("w4-ac-4", 4, ("ch7-average-cost",), "mcq",
                 "Average cost bottoms out exactly where:",
                 ("Marginal cost crosses it from below",
                  "Marginal cost hits zero",
                  "Fixed cost equals variable cost",
                  "Output is at its largest"),
                 0),
        Question("w4-ac-diag", 4, ("ch7-average-cost",), "mcq",
                 "Read the cost curves: at the marked point, MC crosses AC and average cost is at its minimum. Why must the minimum sit at the crossing?",
                 ("Left of it MC is below AC and pulls the average down; right of it MC is above and pushes it up",
                  "Because fixed costs disappear at that output",
                  "It's a drawing convention, nothing more",
                  "Because demand is elastic there"),
                 0,
                 diagram={"xlab": "Output", "ylab": "Cost per unit",
                          "lines": [
                              {"pts": [[15, 70], [30, 52], [50, 42], [70, 46], [90, 58]],
                               "label": "AC", "color": "terracotta"},
                              {"pts": [[15, 40], [30, 30], [45, 36], [60, 52], [80, 78]],
                               "label": "MC", "color": "sage"},
                          ],
                          "points": [{"q": 50, "p": 42, "label": "min"}]}),
        Question("w4-shut-3", 4, ("ch7-breakeven-shutdown",), "mcq",
                 "Tools fetch 25 at market. Your smithy's avoidable costs run 30 per tool; tonight's upkeep of 14 is owed regardless. Tonight you should:",
                 ("Pause production — the price doesn't even cover the avoidable costs",
                  "Produce anyway, to 'help pay' the upkeep",
                  "Exit the tool trade forever",
                  "Raise output to spread the upkeep thinner"),
                 0),
        Question("w4-shut-4", 4, ("ch7-breakeven-shutdown",), "mcq",
                 "Same smithy, better market: price 25, avoidable cost 18 per tool, upkeep still 14. Now?",
                 ("Produce — each tool clears 7 above avoidable costs and chips away at upkeep",
                  "Pause — 25 is less than 18 plus 14",
                  "Exit immediately",
                  "Produce only if upkeep somehow falls"),
                 0),
        Question("w4-shut-free", 4, ("ch7-breakeven-shutdown",), "free",
                 "In a sentence: why might a merchant keep a money-losing bakery running tonight rather than pausing it?",
                 rubric="Credit: if price covers avoidable/variable costs, running contributes something toward fixed upkeep that is owed anyway; pausing loses that contribution.",
                 keywords=("fixed", "upkeep", "variable", "cover", "contribut",
                           "avoidable")),
        # ---- Depth pass, week 5: competition & monopoly ----
        Question("w5-pt-2", 5, ("ch8-price-taker",), "mcq",
                 "Grain has dozens of sellers with identical sacks. You list yours 20% above the going price. Most likely:",
                 ("Nobody buys — the order book offers the same grain cheaper",
                  "Buyers pay extra out of admiration",
                  "The Crown fines you for ambition",
                  "Rivals politely raise their prices to match"),
                 0),
        Question("w5-pt-3", 5, ("ch8-price-taker",), "mcq",
                 "A price taker's real decision is:",
                 ("How much to sell at the going price — not what the price is",
                  "What price to set",
                  "Which buyers deserve their goods",
                  "When to advertise"),
                 0),
        Question("w5-pt-4", 5, ("ch8-price-taker",), "mcq",
                 "Why can't wool sellers simply all agree that 'the price is 60' (with no compact to bind them)?",
                 ("Each one gains by shading to 59 and taking the volume — so someone always does",
                  "Because the Crown sets wool prices",
                  "Because buyers refuse round numbers",
                  "They can — informal agreement is self-enforcing"),
                 0),
        Question("w5-pt-free", 5, ("ch8-price-taker",), "free",
                 "In a sentence: why do your grain asks fill instantly at the market price but sit unfilled a few coppers above it?",
                 rubric="Credit: with many sellers of an identical good, buyers switch costlessly; the demand facing one seller is effectively flat at the market price.",
                 keywords=("substitute", "same", "cheaper", "competition",
                           "elastic", "identical"),
                 context_tags=("trade",)),
        Question("w5-bar-2", 5, ("ch9-barriers",), "mcq",
                 "The glowdye license is a barrier to entry because:",
                 ("It legally caps how many may sell, protecting the holders' markup",
                  "It certifies glowdye quality",
                  "It lowers holders' input costs",
                  "It makes buyers' demand inelastic"),
                 0, context_tags=("license",)),
        Question("w5-bar-3", 5, ("ch9-barriers",), "mcq",
                 "Which of these is NOT a barrier to entry?",
                 ("A rival who simply prices lower than you",
                  "A required royal license",
                  "Control of the only ore mine",
                  "Costs that only pay off at enormous scale"),
                 0),
        Question("w5-bar-4", 5, ("ch9-barriers",), "mcq",
                 "Why do merchants bid so fiercely for glowdye licenses at auction?",
                 ("The license buys freedom from entry — a claim on future monopoly profits",
                  "Prestige, mostly",
                  "The Crown compels every merchant to bid",
                  "Licenses reduce the cost of making glowdye"),
                 0, context_tags=("license",)),
        Question("w5-bar-free", 5, ("ch9-barriers",), "free",
                 "In a sentence or two: what would happen to glowdye prices if the Crown suddenly issued unlimited licenses, and why?",
                 rubric="Credit: entry shifts supply right; price falls toward cost as monopoly profits are competed away.",
                 keywords=("entry", "supply", "fall", "compete", "profit",
                           "down"),
                 context_tags=("license",)),
        Question("w5-mr-4", 5, ("ch9-mr-lt-p",), "mcq",
                 "A monopolist sells 4 vials at 60. To sell a fifth, the price must drop to 55 on all five. The marginal revenue of that fifth vial:",
                 ("35 — the 55 gained minus the 20 surrendered on the first four",
                  "55 — the new price",
                  "60 — the old price",
                  "275 — total revenue"),
                 0),
        Question("w5-mr-5", 5, ("ch9-mr-lt-p",), "mcq",
                 "Because marginal revenue sits below price, a monopolist stops short of:",
                 ("The output a competitive market would have produced",
                  "Producing anything at all",
                  "Charging above its costs",
                  "Ever cutting its costs"),
                 0),
        Question("w5-entry-2", 5, ("ch9-entry-profits",), "mcq",
                 "The Crier reports bakers are minting money. Three new bakeries open within the week. Expect:",
                 ("Bread supply to shift right — price falls, and the spoils spread thinner",
                  "Bread prices to rise with all the excitement",
                  "Old bakers' profits to grow",
                  "Demand for bread to shrink"),
                 0),
        Question("w5-entry-3", 5, ("ch9-entry-profits",), "mcq",
                 "In a market anyone may enter, entry keeps coming until:",
                 ("Profits fall to ordinary levels — no free lunch left to chase",
                  "The price reaches zero",
                  "Only one seller remains",
                  "The Crown declares the market full"),
                 0),
        Question("w5-entry-diag", 5, ("ch9-entry-profits",), "mcq",
                 "Fat profits lured new sellers in, moving supply from S to the dashed S′. The chart shows the market settling at E′, meaning:",
                 ("Price falls and quantity rises as entry competes the profits away",
                  "Price and quantity both fall",
                  "Price rises to reward the newcomers",
                  "Nothing changes for buyers"),
                 0,
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[0, 0], [100, 100]], "label": "S", "color": "sage"},
                              {"pts": [[30, 0], [100, 70]], "label": "S′",
                               "color": "sage", "dashed": True},
                              {"pts": [[0, 100], [100, 0]], "label": "D",
                               "color": "terracotta"},
                          ],
                          "points": [{"q": 50, "p": 50, "label": "E"},
                                     {"q": 65, "p": 35, "label": "E′"}]}),
        # ---- Depth pass, week 6: externalities & the commons ----
        Question("w6-psc-2", 6, ("ch12-private-social",), "mcq",
                 "Your smelter's ledger shows 30c of coal per iron. The neighbors' laundry takes ~10c of soot damage per iron. The SOCIAL cost per iron is:",
                 ("40c — your private cost plus the harm that never touches your ledger",
                  "30c — ledgers don't lie",
                  "10c — only the soot counts",
                  "20c — costs net out"),
                 0),
        Question("w6-psc-3", 6, ("ch12-private-social",), "mcq",
                 "Left entirely alone, a smoky trade will produce:",
                 ("More than the socially best amount — producers don't pay the full cost",
                  "Less than the socially best amount",
                  "Exactly the right amount",
                  "Nothing at all"),
                 0),
        Question("w6-psc-4", 6, ("ch12-private-social",), "mcq",
                 "Flip it: your herb garden's blossoms feed the town's bees, and everyone's orchards yield more. Left alone, herb gardens will be:",
                 ("Underprovided — you never collect the benefit your flowers spill over",
                  "Overprovided — flowers are seductive",
                  "Provided exactly right",
                  "Banned by the beekeepers"),
                 0),
        Question("w6-psc-free", 6, ("ch12-private-social",), "free",
                 "In a sentence: whose costs does the market price of iron reflect, and whose does it miss?",
                 rubric="Credit: it reflects producers' private costs; it misses the external harm borne by third parties (soot on neighbors).",
                 keywords=("private", "social", "third", "neighbor", "soot",
                           "external")),
        Question("w6-pig-2", 6, ("ch12-pigouvian",), "mcq",
                 "The soot levy charges 3c per unit of smoke. It fixes the incentive because:",
                 ("It makes the neighbors' harm show up on the polluter's own ledger",
                  "It bans smoke outright",
                  "It pays polluters to relocate",
                  "It raises every price equally, smoky or clean"),
                 0),
        Question("w6-pig-3", 6, ("ch12-pigouvian",), "mcq",
                 "After the levy lands, who cuts their smoke the MOST?",
                 ("Whoever can abate most cheaply — for them, cleaning up beats paying",
                  "Everyone, in exactly equal measure",
                  "Only the largest producers",
                  "Nobody — taxes never change behavior"),
                 0),
        Question("w6-pig-4", 6, ("ch12-pigouvian", "ch2-marginal-thinking"), "mcq",
                 "A scrubber costs 250c and trims your levy bill by 60c a night. Installing it makes sense when:",
                 ("You'll run long enough that the avoided levies outweigh the 250c",
                  "Never — 250c is 250c",
                  "Always — clean is priceless",
                  "Only if the Crown pays for it"),
                 0),
        Question("w6-pig-free", 6, ("ch12-pigouvian",), "free",
                 "In a sentence: why might the Crown prefer a per-unit soot levy over banning chimneys outright?",
                 rubric="Credit: a levy lets production continue where it's worth more than the harm, and abatement happens where it's cheapest; a ban destroys valuable output indiscriminately.",
                 keywords=("efficient", "value", "cheapest", "still",
                           "incentive", "worth")),
        Question("w6-com-4", 6, ("ch13-commons",), "mcq",
                 "Every extra cast today shrinks everyone's catch tomorrow. Of that tomorrow-cost, you personally bear:",
                 ("Only a sliver — most of it falls on the other anglers",
                  "All of it",
                  "None of it, ever",
                  "Exactly half"),
                 0, context_tags=("fishery", "fishing_cast")),
        Question("w6-com-5", 6, ("ch13-commons",), "mcq",
                 "Which fix gives each angler a personal reason to leave fish for tomorrow?",
                 ("Tradable catch shares they own and can sell",
                  "A heartfelt poster about restraint",
                  "A one-day festival of fishing",
                  "Lower fish prices"),
                 0, context_tags=("fishery",)),
        Question("w6-pub-2", 6, ("ch13-public-goods",), "mcq",
                 "The town lighthouse guides every ship, contributor or not. Predict the voluntary lighthouse fund:",
                 ("Chronically short — each captain hopes the others will pay",
                  "Overflowing — sailors are generous",
                  "Exactly sufficient",
                  "Illegal"),
                 0),
        Question("w6-pub-3", 6, ("ch13-public-goods",), "mcq",
                 "Which of these is a public good?",
                 ("Flood walls that shelter every shop along the row",
                  "A loaf of bread",
                  "A tapestry in your parlor",
                  "A glowdye license"),
                 0),
        Question("w6-pub-4", 6, ("ch13-public-goods",), "mcq",
                 "Non-rival AND non-excludable describes:",
                 ("The Crier's announcements in the town square",
                  "The fishery — rival, but open to all",
                  "Bread",
                  "A licensed dye recipe"),
                 0),
        Question("w6-pub-free", 6, ("ch13-public-goods",), "free",
                 "In a sentence: why do public goods usually need the Guild or the Crown to organize their funding?",
                 rubric="Credit: non-excludability invites free riding, so voluntary funding underprovides; collective mechanisms (taxes, levies, compacts) solve the contribution problem.",
                 keywords=("free rid", "contribute", "everyone", "tax",
                           "collective", "voluntary")),
        # ---- Depth pass, week 7: oligopoly & antitrust ----
        Question("w7-oli-2", 7, ("ch10-interdependence",), "mcq",
                 "You and one rival each choose High or Low prices. Your payoffs: both High, 100; you Low while they're High, 140; both Low, 60; you High while they're Low, 30. If they play High, your best answer is:",
                 ("Low — 140 beats 100",
                  "High — dignity matters",
                  "Flip a coin",
                  "Leave the market"),
                 0),
        Question("w7-oli-3", 7, ("ch10-interdependence",), "mcq",
                 "What makes an oligopoly different from a market of hundreds of sellers?",
                 ("Each seller's best move depends on what specific, named rivals will do",
                  "Oligopolists don't want profits",
                  "Buyers stop comparing prices",
                  "The Crown assigns quantities"),
                 0),
        Question("w7-oli-4", 7, ("ch10-interdependence",), "mcq",
                 "Same payoffs as before, and your rival reasons exactly like you. Where do you both end up?",
                 ("Both Low — each undercuts, and both wish they hadn't",
                  "Both High — cooperation is automatic",
                  "You High, them Low, forever",
                  "No outcome exists"),
                 0),
        Question("w7-oli-free", 7, ("ch10-interdependence",), "free",
                 "In a sentence: why does the very logic that tempts you to undercut also guarantee your rival is tempted too?",
                 rubric="Credit: symmetric incentives / dominant strategy — undercutting is each player's best response regardless of the other's move, producing the dilemma.",
                 keywords=("dominant", "both", "incentive", "undercut",
                           "dilemma", "same")),
        Question("w7-cart-3", 7, ("ch10-cartel-cheating",), "mcq",
                 "Your compact holds cloth at 180. Tonight, quietly shading to 175 would win you most of the fills. The compact's deep problem is:",
                 ("Every signatory sees the same 175 — so sooner or later, someone shades",
                  "The Crown forbids selling below 180",
                  "Buyers prefer paying more",
                  "Cloth spoils at lower prices"),
                 0, context_tags=("compact_created",)),
        Question("w7-cart-4", 7, ("ch10-cartel-cheating",), "mcq",
                 "Cartels hold together best when:",
                 ("Members are few, and cheating is easy to spot and punish",
                  "Members are many, and sales are secret",
                  "Prices are posted nowhere",
                  "Anyone may enter the market freely"),
                 0),
        Question("w7-cart-5", 7, ("ch10-cartel-cheating",), "mcq",
                 "The Crier publishes every trade in the square. For a cartel, this makes things:",
                 ("Easier to police internally — and easier for the Crown to catch",
                  "Entirely impossible",
                  "Completely irrelevant",
                  "Legal, since it's all public"),
                 0, context_tags=("compact_created",)),
        Question("w7-diff-2", 7, ("ch10-differentiation",), "mcq",
                 "A maker's mark on your garments lets you charge a little more because:",
                 ("Some buyers now prefer YOUR garments — your own demand curve tilts, granting slight pricing power",
                  "Marks are required by law",
                  "It lowers your production costs",
                  "It makes all garments identical"),
                 0),
        Question("w7-diff-3", 7, ("ch10-differentiation",), "mcq",
                 "\"Monopolistic competition\" describes a market with:",
                 ("Many sellers, each offering a product that is a little bit its own",
                  "One seller of everything",
                  "Identical products and two sellers",
                  "No possibility of entry"),
                 0),
        Question("w7-diff-4", 7, ("ch10-differentiation",), "mcq",
                 "Unlike a true monopolist, a differentiated garment-maker's pricing power is capped by:",
                 ("Close substitutes hanging one stall over",
                  "The Crown's garment decree",
                  "The weather",
                  "Nothing at all"),
                 0),
        Question("w7-diff-free", 7, ("ch10-differentiation",), "free",
                 "In a sentence: name one way to make your shop's bread genuinely different, and why that lets you nudge the price above your rivals'.",
                 rubric="Credit: any differentiation (quality, recipe, service, location, brand) that makes some buyers prefer it, flattening their willingness to switch on small price gaps.",
                 keywords=("brand", "quality", "prefer", "loyal", "substitute",
                           "different")),
        Question("w7-anti-2", 7, ("ch11-antitrust",), "mcq",
                 "The Crown's antitrust writ properly targets:",
                 ("Concentration and collusion that push prices above competitive levels",
                  "Any merchant who grows large",
                  "High wages for workers",
                  "Goods arriving from other towns"),
                 0),
        Question("w7-anti-3", 7, ("ch11-antitrust",), "mcq",
                 "Petra M. owns most of the wool trade AND colludes with rivals on price. Which remedy answers the COLLUSION specifically?",
                 ("Fines for the price-fixing agreement itself",
                  "Divesting Petra's wool holdings",
                  "A price ceiling on bread",
                  "A subsidy to Petra"),
                 0),
        Question("w7-anti-4", 7, ("ch11-antitrust",), "mcq",
                 "When might the Crown wisely leave a near-monopolist alone?",
                 ("When its dominance comes from a better product at a lower price — punishing that punishes buyers",
                  "Whenever it employs many workers",
                  "When it donates to the Guild",
                  "Never — size itself is the crime"),
                 0),
        Question("w7-anti-free", 7, ("ch11-antitrust",), "free",
                 "In a sentence or two: why is \"big\" not automatically \"bad\" in antitrust?",
                 rubric="Credit: the test is harm to buyers (prices, output, innovation); scale can reflect efficiency or a better product, and breaking that up hurts consumers.",
                 keywords=("consumer", "price", "harm", "efficien", "scale",
                           "better")),
        # ---- Diagram questions: read the chart, then answer ----
        Question("w2-diag-equil", 2, ("ch3-equilibrium",), "mcq",
                 "Read the chart. Where does this market clear?",
                 ("At E, around a price of 50",
                  "At a price of 100 — the highest anyone will pay",
                  "At a price of 0 — competition drives price to nothing",
                  "It never clears; supply and demand are different lines"),
                 0, diagram=_SD),
        Question("w2-diag-demand-shift", 2, ("ch3-shift-vs-movement", "ch3-demand-vs-qd"), "mcq",
                 "The Lantern Festival floods the town with garment buyers. The dashed line shows what happened. What is it?",
                 ("A movement along the old demand curve",
                  "The whole demand curve shifted right: more buyers at every price",
                  "Supply shifted left",
                  "Just a price change — the curves are the same"),
                 1, context_tags=("festival",),
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[0, 0], [100, 100]], "label": "S", "color": "sage"},
                              {"pts": [[0, 100], [100, 0]], "label": "D", "color": "terracotta"},
                              {"pts": [[30, 100], [100, 30]], "label": "D′",
                               "color": "terracotta", "dashed": True},
                          ],
                          "points": [{"q": 50, "p": 50, "label": "E"},
                                     {"q": 65, "p": 65, "label": "E′"}]}),
        Question("w2-diag-supply-shock", 2, ("ch3-equilibrium", "ch3-shortage-surplus"), "mcq",
                 "Drought withers the grain fields — supply shifts from S to the dashed S′. Comparing E′ to E:",
                 ("Price rises and quantity traded falls",
                  "Price falls and quantity traded rises",
                  "Both price and quantity rise",
                  "Nothing changes until the Crown acts"),
                 0, context_tags=("drought",),
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[0, 0], [100, 100]], "label": "S", "color": "sage"},
                              {"pts": [[0, 30], [70, 100]], "label": "S′",
                               "color": "sage", "dashed": True},
                              {"pts": [[0, 100], [100, 0]], "label": "D", "color": "terracotta"},
                          ],
                          "points": [{"q": 50, "p": 50, "label": "E"},
                                     {"q": 35, "p": 65, "label": "E′"}]}),
        Question("w3-diag-ceiling", 3, ("ch3-price-ceiling", "ch3-shortage-surplus"), "mcq",
                 "The Crown pins the price at the ceiling line. Reading the chart at that price:",
                 ("A shortage: buyers want 70 units but sellers bring only 30",
                  "A surplus: sellers bring 70 but buyers want only 30",
                  "The market still clears at E",
                  "Sellers bring more than they did at equilibrium"),
                 0, context_tags=("ceiling",),
                 diagram={**_SD, "hline": {"p": 30, "label": "ceiling"},
                          "guides": [{"q": 30, "p": 30}, {"q": 70, "p": 30}]}),
        Question("w3-diag-shortage-size", 3, ("ch3-shortage-surplus",), "mcq",
                 "Same ceiling, one more read: how large is the shortage at the ceiling price of 30?",
                 ("40 units — buyers want 70, sellers bring 30",
                  "70 units — everything buyers want",
                  "30 units — everything sellers bring",
                  "Zero: shortages are impossible at a legal price"),
                 0, context_tags=("ceiling",),
                 diagram={**_SD, "hline": {"p": 30, "label": "ceiling"},
                          "guides": [{"q": 30, "p": 30}, {"q": 70, "p": 30}]}),
        Question("w3-diag-floor", 3, ("ch3-price-ceiling", "ch3-shortage-surplus"), "mcq",
                 "Now the Crown sets a FLOOR above equilibrium (say, to help wool sellers). The chart says:",
                 ("A surplus: sellers bring 70 units but buyers take only 30",
                  "A shortage: buyers want more than sellers bring",
                  "The floor has no effect",
                  "Quantity traded rises above 50"),
                 0,
                 diagram={**_SD, "hline": {"p": 70, "label": "floor"},
                          "guides": [{"q": 30, "p": 70}, {"q": 70, "p": 70}]}),
        Question("w3-diag-elastic", 3, ("ch5-elasticity-def", "ch5-determinants"), "mcq",
                 "Two goods sell at 50 today. Curve A is steep; curve B is flat. Which is the luxury tapestry — the thing people abandon the moment it gets dear?",
                 ("B — the flat curve: quantity collapses when price rises",
                  "A — the steep curve: quantity barely moves",
                  "Both are equally elastic at E",
                  "Neither; slope says nothing about buyers"),
                 0,
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[40, 80], [60, 20]], "label": "A", "color": "terracotta"},
                              {"pts": [[0, 75], [100, 25]], "label": "B", "color": "sky"},
                          ],
                          "points": [{"q": 50, "p": 50, "label": ""}]}),
        Question("w3-diag-tr", 3, ("ch5-total-revenue",), "mcq",
                 "Bread demand is steep (inelastic). The price climbs from point B to point A. What happens to bakers' total revenue?",
                 ("It rises — the price gain outweighs the few loaves lost",
                  "It falls — buyers flee to substitutes",
                  "It stays exactly the same",
                  "It becomes zero at any price above B"),
                 0,
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[20, 95], [70, 20]], "label": "D", "color": "terracotta"},
                          ],
                          "points": [{"q": 40, "p": 65, "label": "A"},
                                     {"q": 56, "p": 41, "label": "B"}]}),
        Question("w4-diag-returns", 4, ("ch7-diminishing-returns",), "mcq",
                 "Your facility's output as you add workers. Each new hire adds less than the last. The flattening curve shows:",
                 ("Diminishing marginal returns — the workshop gets crowded",
                  "Rising fixed costs",
                  "Falling demand for your good",
                  "Workers becoming lazier each day"),
                 0, context_tags=("workers",),
                 diagram={"xlab": "Workers", "ylab": "Output",
                          "lines": [
                              {"pts": [[5, 12], [25, 42], [45, 60], [65, 71], [90, 77]],
                               "label": "Total output", "color": "sage"},
                          ]}),
        Question("w4-diag-costs", 4, ("ch7-fixed-variable",), "mcq",
                 "Two cost lines for your bakery. Why is FC flat?",
                 ("Fixed costs are owed no matter how much you produce",
                  "Flour gets cheaper as you bake more",
                  "The Crown caps costs by decree",
                  "It isn't flat — costs always rise"),
                 0,
                 diagram={"xlab": "Output", "ylab": "Coppers",
                          "lines": [
                              {"pts": [[0, 30], [95, 30]], "label": "FC", "color": "ink"},
                              {"pts": [[0, 30], [90, 85]], "label": "TC", "color": "terracotta"},
                          ]}),
        Question("w5-diag-mr", 5, ("ch9-mr-lt-p",), "mcq",
                 "A glowdye monopolist faces demand D, but its marginal revenue line MR sits below D. Why?",
                 ("To sell one more vial it must cut the price on every vial",
                  "Monopolists are barred from charging the demand price",
                  "MR is always half of total cost",
                  "The chart is drawn wrong; MR equals D"),
                 0, context_tags=("license",),
                 diagram={"xlab": "Quantity", "ylab": "Price",
                          "lines": [
                              {"pts": [[0, 90], [90, 0]], "label": "D", "color": "terracotta"},
                              {"pts": [[0, 90], [45, 0]], "label": "MR", "color": "ink",
                               "dashed": True},
                          ]}),
        Question("w6-diag-commons", 6, ("ch13-commons",), "mcq",
                 "The fishery's stock, day by day, under open access. Why does the line keep falling?",
                 ("No one owns the stock, so no one bears the cost of the last fish taken",
                  "Fish naturally die out in autumn",
                  "The Crown is secretly draining the harbor",
                  "Fishing technology got worse"),
                 0, context_tags=("fishery",),
                 diagram={"xlab": "Day", "ylab": "Fish stock",
                          "lines": [
                              {"pts": [[5, 85], [20, 74], [40, 58], [60, 40], [75, 25], [90, 13]],
                               "label": "Stock", "color": "sky"},
                          ]}),
    ]
}


def questions_for_week(week: int) -> list[Question]:
    return [q for q in QUESTIONS.values() if q.week == week]


def questions_for_context(week: int, tags: set[str]) -> list[Question]:
    return [q for q in QUESTIONS.values()
            if q.week <= week and tags.intersection(q.context_tags)]
