"""initial

Revision ID: ff93cfaaa47b
Revises: 
Create Date: 2026-06-11 10:17:21.013174
"""
from alembic import op
import sqlalchemy as sa


revision = 'ff93cfaaa47b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_magic_tokens_email'), 'magic_tokens', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('is_instructor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worlds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('join_code', sa.String(length=12), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('market_rules', sa.JSON(), nullable=False),
    sa.Column('smog', sa.Integer(), nullable=False),
    sa.Column('fish_stock', sa.Integer(), nullable=False),
    sa.Column('fishing_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_code'),
    sa.UniqueConstraint('section_id')
    )
    op.create_table('compacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('dissolved_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compacts_world_id'), 'compacts', ['world_id'], unique=False)
    op.create_table('crier_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crier_world_day', 'crier_posts', ['world_id', 'world_day'], unique=False)
    op.create_table('detected_moments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('endorsed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_moments_world_id'), 'detected_moments', ['world_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('crier_copy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_world_id'), 'interventions', ['world_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('open', sa.Integer(), nullable=True),
    sa.Column('high', sa.Integer(), nullable=True),
    sa.Column('low', sa.Integer(), nullable=True),
    sa.Column('close', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('unfilled_demand', sa.Integer(), nullable=False),
    sa.Column('suppressed_asks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'good_id', 'world_day')
    )
    op.create_index(op.f('ix_price_snapshots_world_id'), 'price_snapshots', ['world_id'], unique=False)
    op.create_table('scheduled_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_events_world_id'), 'scheduled_events', ['world_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('banner', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_world_id'), 'teams', ['world_id'], unique=False)
    op.create_table('world_day_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('gini_bp', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('active_players', sa.Integer(), nullable=False),
    sa.Column('smog', sa.Integer(), nullable=False),
    sa.Column('fish_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'world_day')
    )
    op.create_index(op.f('ix_world_day_stats_world_id'), 'world_day_stats', ['world_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_name', sa.String(length=80), nullable=False),
    sa.Column('coins', sa.BigInteger(), nullable=False),
    sa.Column('effort', sa.Integer(), nullable=False),
    sa.Column('aptitude_good', sa.String(length=40), nullable=True),
    sa.Column('is_npc', sa.Boolean(), nullable=False),
    sa.Column('bankrupt_resets', sa.Integer(), nullable=False),
    sa.Column('last_active_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'user_id')
    )
    op.create_index(op.f('ix_players_world_id'), 'players', ['world_id'], unique=False)
    op.create_table('check_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.String(length=60), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_attempts_player_id'), 'check_attempts', ['player_id'], unique=False)
    op.create_index(op.f('ix_check_attempts_world_id'), 'check_attempts', ['world_id'], unique=False)
    op.create_table('compact_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('compact_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('joined_day', sa.Integer(), nullable=False),
    sa.Column('left_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compact_id'], ['compacts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compact_id', 'player_id')
    )
    op.create_index(op.f('ix_compact_members_compact_id'), 'compact_members', ['compact_id'], unique=False)
    op.create_table('econ_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor_player_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_econ_events_kind'), 'econ_events', ['kind'], unique=False)
    op.create_index('ix_econ_events_world', 'econ_events', ['world_id', 'id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('workers', sa.Integer(), nullable=False),
    sa.Column('scrubber', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_player_id'), 'facilities', ['player_id'], unique=False)
    op.create_index(op.f('ix_facilities_world_id'), 'facilities', ['world_id'], unique=False)
    op.create_table('fishing_catches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('fish_qty', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('trophy', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fishing_catches_player_id'), 'fishing_catches', ['player_id'], unique=False)
    op.create_index(op.f('ix_fishing_catches_world_id'), 'fishing_catches', ['world_id'], unique=False)
    op.create_table('guild_loans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('principal', sa.Integer(), nullable=False),
    sa.Column('outstanding', sa.Integer(), nullable=False),
    sa.Column('rate_bp_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_loans_player_id'), 'guild_loans', ['player_id'], unique=False)
    op.create_index(op.f('ix_guild_loans_world_id'), 'guild_loans', ['world_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id', 'good_id')
    )
    op.create_index(op.f('ix_inventories_player_id'), 'inventories', ['player_id'], unique=False)
    op.create_index(op.f('ix_inventories_world_id'), 'inventories', ['world_id'], unique=False)
    op.create_table('license_bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('auction_id', sa.String(length=60), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'player_id')
    )
    op.create_index(op.f('ix_license_bids_world_id'), 'license_bids', ['world_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_world_id'), 'licenses', ['world_id'], unique=False)
    op.create_table('mastery_estimates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('lo_id', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id', 'lo_id')
    )
    op.create_index(op.f('ix_mastery_estimates_player_id'), 'mastery_estimates', ['player_id'], unique=False)
    op.create_index(op.f('ix_mastery_estimates_world_id'), 'mastery_estimates', ['world_id'], unique=False)
    op.create_table('merchant_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id')
    )
    op.create_index(op.f('ix_merchant_runs_player_id'), 'merchant_runs', ['player_id'], unique=False)
    op.create_index(op.f('ix_merchant_runs_world_id'), 'merchant_runs', ['world_id'], unique=False)
    op.create_table('npc_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('npc_player_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('p_low', sa.Integer(), nullable=False),
    sa.Column('p_high', sa.Integer(), nullable=False),
    sa.Column('qty_per_day', sa.Integer(), nullable=False),
    sa.Column('price_mult', sa.Float(), nullable=False),
    sa.Column('qty_mult', sa.Float(), nullable=False),
    sa.Column('revert_day', sa.Integer(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['npc_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'good_id', 'side')
    )
    op.create_index(op.f('ix_npc_schedules_world_id'), 'npc_schedules', ['world_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('placed_day', sa.Integer(), nullable=False),
    sa.Column('expires_day', sa.Integer(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_book', 'orders', ['world_id', 'good_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_player_id'), 'orders', ['player_id'], unique=False)
    op.create_index(op.f('ix_orders_world_id'), 'orders', ['world_id'], unique=False)
    op.create_table('player_achievements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.String(length=60), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'achievement_id')
    )
    op.create_index(op.f('ix_player_achievements_player_id'), 'player_achievements', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_achievements_world_id'), 'player_achievements', ['world_id'], unique=False)
    op.create_table('player_cosmetics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('cosmetic_id', sa.String(length=60), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'cosmetic_id')
    )
    op.create_index(op.f('ix_player_cosmetics_player_id'), 'player_cosmetics', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_cosmetics_world_id'), 'player_cosmetics', ['world_id'], unique=False)
    op.create_table('player_day_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('coins', sa.BigInteger(), nullable=False),
    sa.Column('net_worth', sa.BigInteger(), nullable=False),
    sa.Column('participation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id', 'world_day')
    )
    op.create_index(op.f('ix_player_day_stats_player_id'), 'player_day_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_day_stats_world_id'), 'player_day_stats', ['world_id'], unique=False)
    op.create_table('puzzle_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('guesses', sa.JSON(), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id', 'world_day')
    )
    op.create_index(op.f('ix_puzzle_attempts_player_id'), 'puzzle_attempts', ['player_id'], unique=False)
    op.create_index(op.f('ix_puzzle_attempts_world_id'), 'puzzle_attempts', ['world_id'], unique=False)
    op.create_table('shop_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sold_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'player_id', 'good_id')
    )
    op.create_index(op.f('ix_shop_listings_player_id'), 'shop_listings', ['player_id'], unique=False)
    op.create_index(op.f('ix_shop_listings_world_id'), 'shop_listings', ['world_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('best', sa.Integer(), nullable=False),
    sa.Column('last_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'kind')
    )
    op.create_index(op.f('ix_streaks_player_id'), 'streaks', ['player_id'], unique=False)
    op.create_index(op.f('ix_streaks_world_id'), 'streaks', ['world_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('good_id', sa.String(length=40), nullable=False),
    sa.Column('buyer_player_id', sa.Uuid(), nullable=False),
    sa.Column('seller_player_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['seller_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_tape', 'trades', ['world_id', 'good_id', 'world_day'], unique=False)
    op.create_index(op.f('ix_trades_world_id'), 'trades', ['world_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('world_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tutor_msgs', 'tutor_messages', ['world_id', 'player_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutor_msgs', table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_trades_world_id'), table_name='trades')
    op.drop_index('ix_trades_tape', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_streaks_world_id'), table_name='streaks')
    op.drop_index(op.f('ix_streaks_player_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_shop_listings_world_id'), table_name='shop_listings')
    op.drop_index(op.f('ix_shop_listings_player_id'), table_name='shop_listings')
    op.drop_table('shop_listings')
    op.drop_index(op.f('ix_puzzle_attempts_world_id'), table_name='puzzle_attempts')
    op.drop_index(op.f('ix_puzzle_attempts_player_id'), table_name='puzzle_attempts')
    op.drop_table('puzzle_attempts')
    op.drop_index(op.f('ix_player_day_stats_world_id'), table_name='player_day_stats')
    op.drop_index(op.f('ix_player_day_stats_player_id'), table_name='player_day_stats')
    op.drop_table('player_day_stats')
    op.drop_index(op.f('ix_player_cosmetics_world_id'), table_name='player_cosmetics')
    op.drop_index(op.f('ix_player_cosmetics_player_id'), table_name='player_cosmetics')
    op.drop_table('player_cosmetics')
    op.drop_index(op.f('ix_player_achievements_world_id'), table_name='player_achievements')
    op.drop_index(op.f('ix_player_achievements_player_id'), table_name='player_achievements')
    op.drop_table('player_achievements')
    op.drop_index(op.f('ix_orders_world_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_player_id'), table_name='orders')
    op.drop_index('ix_orders_book', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_npc_schedules_world_id'), table_name='npc_schedules')
    op.drop_table('npc_schedules')
    op.drop_index(op.f('ix_merchant_runs_world_id'), table_name='merchant_runs')
    op.drop_index(op.f('ix_merchant_runs_player_id'), table_name='merchant_runs')
    op.drop_table('merchant_runs')
    op.drop_index(op.f('ix_mastery_estimates_world_id'), table_name='mastery_estimates')
    op.drop_index(op.f('ix_mastery_estimates_player_id'), table_name='mastery_estimates')
    op.drop_table('mastery_estimates')
    op.drop_index(op.f('ix_licenses_world_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_license_bids_world_id'), table_name='license_bids')
    op.drop_table('license_bids')
    op.drop_index(op.f('ix_inventories_world_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_player_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_guild_loans_world_id'), table_name='guild_loans')
    op.drop_index(op.f('ix_guild_loans_player_id'), table_name='guild_loans')
    op.drop_table('guild_loans')
    op.drop_index(op.f('ix_fishing_catches_world_id'), table_name='fishing_catches')
    op.drop_index(op.f('ix_fishing_catches_player_id'), table_name='fishing_catches')
    op.drop_table('fishing_catches')
    op.drop_index(op.f('ix_facilities_world_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_player_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index('ix_econ_events_world', table_name='econ_events')
    op.drop_index(op.f('ix_econ_events_kind'), table_name='econ_events')
    op.drop_table('econ_events')
    op.drop_index(op.f('ix_compact_members_compact_id'), table_name='compact_members')
    op.drop_table('compact_members')
    op.drop_index(op.f('ix_check_attempts_world_id'), table_name='check_attempts')
    op.drop_index(op.f('ix_check_attempts_player_id'), table_name='check_attempts')
    op.drop_table('check_attempts')
    op.drop_index(op.f('ix_players_world_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_world_day_stats_world_id'), table_name='world_day_stats')
    op.drop_table('world_day_stats')
    op.drop_index(op.f('ix_teams_world_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_scheduled_events_world_id'), table_name='scheduled_events')
    op.drop_table('scheduled_events')
    op.drop_index(op.f('ix_price_snapshots_world_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_interventions_world_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_detected_moments_world_id'), table_name='detected_moments')
    op.drop_table('detected_moments')
    op.drop_index('ix_crier_world_day', table_name='crier_posts')
    op.drop_table('crier_posts')
    op.drop_index(op.f('ix_compacts_world_id'), table_name='compacts')
    op.drop_table('compacts')
    op.drop_table('worlds')
    op.drop_table('sections')
    op.drop_table('courses')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_magic_tokens_email'), table_name='magic_tokens')
    op.drop_table('magic_tokens')
    op.drop_table('institutions')
    # ### end Alembic commands ###
